# Generated by Django 3.1.5 on 2021-03-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('agent_title', models.CharField(max_length=100, verbose_name='Profile Title')),
                ('agent_desription', models.TextField(verbose_name='Description')),
                ('agent_contact', models.CharField(max_length=20, verbose_name='Contact')),
                ('agent_address', models.CharField(max_length=100, verbose_name='Address')),
                ('agent_email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('buy_title', models.CharField(max_length=100, verbose_name='Profile Title')),
                ('buy_price', models.CharField(max_length=20, verbose_name='Price')),
                ('buy_desription', models.TextField(verbose_name='Description')),
                ('buy_contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Buy',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('pro_title', models.CharField(max_length=100, verbose_name='Profile Title')),
                ('pro_sale', models.CharField(max_length=20, verbose_name='Sales or Rent')),
                ('pro_price', models.CharField(max_length=20, verbose_name='Price')),
                ('pro_desription', models.TextField(verbose_name='Description')),
                ('pro_contact', models.CharField(max_length=20, verbose_name='Contact')),
                ('pro_date', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField()),
                ('sponsored', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Property',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('rent_title', models.CharField(max_length=100, verbose_name='Profile Title')),
                ('rent_price', models.CharField(max_length=20, verbose_name='Price')),
                ('rent_desription', models.TextField(verbose_name='Description')),
                ('rent_contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('rent_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rent',
            },
        ),
    ]
