# Generated by Django 3.1.5 on 2021-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spon_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('spon_title', models.CharField(max_length=100)),
                ('spon_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spon_desription', models.TextField()),
            ],
        ),
    ]
