# Generated by Django 3.0.3 on 2021-01-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='First name')),
                ('l_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('username', models.CharField(max_length=100, verbose_name='User name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
