# Generated by Django 3.1.5 on 2021-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='sponsored',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
