# Generated by Django 3.1.5 on 2021-02-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsored',
            options={'verbose_name_plural': 'Sponsored'},
        ),
        migrations.AlterField(
            model_name='sponsored',
            name='spon_desription',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sponsored',
            name='spon_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='sponsored',
            name='spon_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='sponsored',
            name='spon_title',
            field=models.CharField(max_length=100, verbose_name='Profile Title'),
        ),
    ]
