# Generated by Django 3.1.5 on 2021-02-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name_plural': 'Biography'},
        ),
        migrations.AlterField(
            model_name='biography',
            name='bio_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='bio_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='bio_title',
            field=models.CharField(max_length=100, verbose_name='Profile Title'),
        ),
    ]
