# Generated by Django 3.1.5 on 2021-03-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('pro_title', models.CharField(max_length=100, verbose_name='Profile Title')),
                ('pro_sale', models.CharField(max_length=20, verbose_name='Sales or Rent')),
                ('pro_price', models.CharField(max_length=20, verbose_name='Price')),
                ('pro_desription', models.TextField(verbose_name='Description')),
                ('pro_contact', models.CharField(max_length=20, verbose_name='Contact')),
                ('pro_date', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField()),
                ('sponsored', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'AddProperty',
            },
        ),
    ]
