# Generated by Django 3.1.5 on 2021-03-06 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='User Image')),
                ('user_name', models.CharField(max_length=150, verbose_name='User Name')),
                ('user_number', models.CharField(max_length=20, verbose_name='Founder Number')),
                ('user_email', models.EmailField(max_length=150, verbose_name='Founder Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
