# Generated by Django 3.1.5 on 2021-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_addproperty_add_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='property_type',
            field=models.CharField(choices=[('S', 'person_page_obj'), ('F', 'person_page_obj'), ('B', 'person_page_obj'), ('R', 'person_page_obj'), ('', 'Please Choose')], default='', max_length=15),
        ),
    ]
