# Generated by Django 3.1.5 on 2021-03-09 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Edit',
            },
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='property_type',
            field=models.CharField(choices=[('S', 'Sponsored'), ('F', 'Featured'), ('B', 'Buy'), ('R', 'Rent'), ('', 'Please Choose')], default='', max_length=15),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='edit',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.addproperty'),
        ),
    ]
