# Generated by Django 3.1.5 on 2021-03-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_addproperty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproperty',
            old_name='featured',
            new_name='buy',
        ),
        migrations.RenameField(
            model_name='addproperty',
            old_name='sponsored',
            new_name='rent',
        ),
    ]
