# Generated by Django 3.1.5 on 2021-02-08 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210208_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsored',
            name='spon_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
