# Generated by Django 3.1.5 on 2021-02-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_sponsored_spon_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_img', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('lat_title', models.CharField(max_length=100, verbose_name='Profile Title')),
                ('lat_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('lat_desription', models.TextField(verbose_name='Description')),
                ('lat_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Latest',
            },
        ),
    ]
