# Generated by Django 3.1.5 on 2021-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_addproperty_listing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproperty',
            name='property_type',
        ),
        migrations.AddField(
            model_name='addproperty',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='offer_type',
            field=models.CharField(choices=[('B', 'Buy'), ('R', 'Rent'), ('', 'Please Choose')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='sponsored',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='listing_type',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Dublex', 'Dublex'), ('Flat', 'Flat'), ('Glasshouse', 'Glass House'), ('Story Building', 'Story Building'), ('', 'Please Choose')], default='', max_length=15),
        ),
    ]
