# Generated by Django 3.1.5 on 2021-02-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210215_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='buy_contact',
            new_name='pro_contact',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='buy_contact',
            new_name='rent_contact',
        ),
    ]
