# Generated by Django 3.1.5 on 2021-03-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproperty',
            name='user',
        ),
    ]
