# Generated by Django 3.1.5 on 2021-03-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210309_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='post',
            new_name='user',
        ),
    ]
