# Generated by Django 3.1.5 on 2021-02-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210215_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='buy_contact',
            new_name='agent_contact',
        ),
    ]
