# Generated by Django 3.1.5 on 2021-03-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210309_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='user',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='editor',
        ),
    ]
