# Generated by Django 3.1.5 on 2021-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210325_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='listing_type',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Glasshouse', 'Glass House'), ('Story Building', 'Story Building'), ('', 'Please Choose')], default='', max_length=15),
        ),
    ]
