# Generated by Django 3.1.5 on 2021-03-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210309_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit',
        ),
    ]
