# Generated by Django 3.1.5 on 2021-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210325_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='listing_type',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Glasshouse', 'Glass House'), ('Story Building', 'Story Building'), ('', 'Please Choose')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='offer_type',
            field=models.CharField(choices=[('B', 'Buy'), ('R', 'Rent'), ('', 'Please Choose')], default='', max_length=40),
        ),
    ]
