# Generated by Django 3.1.5 on 2021-02-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210215_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pro_sale',
            field=models.CharField(default=1, max_length=20, verbose_name='Sales or Rent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='pro_contact',
            field=models.CharField(max_length=20, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pro_price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Price'),
        ),
    ]
