# Generated by Django 3.1.5 on 2021-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20210325_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='add_price',
            field=models.CharField(choices=[('1', '&#8358; 100000'), ('2', '&#8358; 150000'), ('3', '&#8358; 200000'), ('4', '&#8358; 250000'), ('5', '&#8358; 300000'), ('6', '&#8358; 350000'), ('7', '&#8358; 400000'), ('8', '&#8358; 450000'), ('', 'Please Choose')], default='', max_length=40),
        ),
    ]
