# Generated by Django 3.1.5 on 2021-02-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210216_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='agent_address',
            field=models.CharField(default=1, max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='agent_email',
            field=models.CharField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent_contact',
            field=models.CharField(max_length=20, verbose_name='Contact'),
        ),
    ]
