# Generated by Django 3.1.5 on 2021-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210325_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='add_price',
            field=models.CharField(choices=[('1', ' 100000'), ('2', ' 150000'), ('3', ' 200000'), ('4', ' 250000'), ('5', ' 300000'), ('6', ' 350000'), ('7', ' 400000'), ('8', ' 450000'), ('', 'Please Choose')], default='', max_length=40),
        ),
    ]
