# Generated by Django 3.1.5 on 2021-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210325_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='add_price',
            field=models.CharField(choices=[('1', ' 100,000'), ('2', ' 150,000'), ('3', ' 200,000'), ('4', ' 250,000'), ('5', ' 300,000'), ('6', ' 350,000'), ('7', ' 400,000'), ('8', ' 450,000'), ('9', ' 500,000'), ('10', ' 550,000'), ('11', ' 600,000'), ('22', ' 650,000'), ('33', ' 700,000'), ('44', ' 750,000'), ('55', ' 800,000'), ('66', ' 850,000'), ('77', ' 900,000'), ('88', ' 950,000'), ('99', ' 1 Million'), ('110', ' 1.5 Million'), ('111', ' 2 Million'), ('222', ' 2.5 Million'), ('333', ' 3 Million'), ('444', ' 3.5 Million'), ('555', ' 4 Million'), ('666', ' 4.5 Million'), ('777', ' 5 Million'), ('', 'Please Choose')], default='', max_length=40),
        ),
    ]
