# Generated by Django 3.1.5 on 2021-02-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210216_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_desription',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buy_desription',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pro_desription',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_desription',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
    ]
