# Generated by Django 3.1.5 on 2021-02-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20210217_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_desription',
            field=models.TextField(max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buy_desription',
            field=models.TextField(max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=400, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_desription',
            field=models.TextField(max_length=400, verbose_name='Description'),
        ),
    ]
