# Generated by Django 3.1.5 on 2021-02-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210217_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pro_desription',
            field=models.TextField(max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=100, verbose_name='Price'),
        ),
    ]
