# Generated by Django 3.1.5 on 2021-03-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210325_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Other Images'),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Other Images'),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Other Images'),
        ),
    ]
