# Generated by Django 3.1.5 on 2021-02-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20210217_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_desription',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buy_desription',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pro_desription',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_desription',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
