# Generated by Django 3.1.5 on 2021-03-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20210330_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
