# Generated by Django 3.1.5 on 2021-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210217_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
    ]
