# Generated by Django 3.1.5 on 2021-03-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210330_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='sponsored',
            field=models.BooleanField(),
        ),
    ]
