# Generated by Django 3.1.5 on 2021-03-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20210218_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buy_price',
            field=models.CharField(max_length=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pro_price',
            field=models.CharField(max_length=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_price',
            field=models.CharField(max_length=20, verbose_name='Price'),
        ),
    ]
