# Generated by Django 3.1.5 on 2021-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20210330_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='add_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Property image'),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='add_title',
            field=models.CharField(max_length=100, verbose_name='Property Name'),
        ),
    ]
