# Generated by Django 3.1.5 on 2021-04-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
